import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              3,
            ),
          ),
          shadowColor: appTheme.black900Dd.withOpacity(0.25),
          elevation: 4,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: colorScheme.onError,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: getFontSize(
            34,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: getFontSize(
            24,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: getFontSize(
            20,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF3E33CD),
    primaryContainer: Color(0XFFFFC732),
    secondary: Color(0XFFFFC732),
    secondaryContainer: Color(0X00393736),
    tertiary: Color(0XFFFFC732),
    tertiaryContainer: Color(0X00393736),

    // Background colors
    background: Color(0XFFFFC732),

    // Surface colors
    surface: Color(0XFFFFC732),
    surfaceTint: Color(0XA9FFFFFF),
    surfaceVariant: Color(0X00393736),

    // Error colors
    error: Color(0XA9FFFFFF),
    errorContainer: Color(0XFF3E33CD),
    onError: Color(0XFF292929),
    onErrorContainer: Color(0XA9FFFFFF),

    // On colors(text colors)
    onBackground: Color(0XFF202023),
    onInverseSurface: Color(0XFF292929),
    onPrimary: Color(0XA9FFFFFF),
    onPrimaryContainer: Color(0XFF202023),
    onSecondary: Color(0XFF202023),
    onSecondaryContainer: Color(0XA9FFFFFF),
    onTertiary: Color(0XFF202023),
    onTertiaryContainer: Color(0XA9FFFFFF),

    // Other colors
    outline: Color(0XA9FFFFFF),
    outlineVariant: Color(0XFFFFC732),
    scrim: Color(0XFFFFC732),
    shadow: Color(0XA9FFFFFF),

    // Inverse colors
    inversePrimary: Color(0XFFFFC732),
    inverseSurface: Color(0XA9FFFFFF),

    // Pending colors
    onSurface: Color(0XFF202023),
    onSurfaceVariant: Color(0XA9FFFFFF),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // BlackDd
  Color get black900Dd => Color(0XDD000000);

  // Blue
  Color get blue50 => Color(0XFFEAEFFF);

  // BlueGray
  Color get blueGray300 => Color(0XFF9098B1);
  Color get blueGray400 => Color(0XFF888888);

  // DeepPurple
  Color get deepPurpleA200 => Color(0XFF795DE3);

  // Gray
  Color get gray50 => Color(0XFFFFF9F9);
  Color get gray900 => Color(0XFF1A1918);
  Color get gray90001 => Color(0XFF202022);
  Color get gray90002 => Color(0XFF121212);

  // Indigo
  Color get indigo500 => Color(0XFF3F32CC);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
